### ISSUE TITLE
Doesn't work with tornado 5

### ISSUE THREAD

**Issue by wjd52** [samr85/KPH#29]
Browser can't access the page if tornado 5 is used. It just hangs indefinitely. Works fine in tornado 4.5

Low priority because I've now reverted back to tornado 4.5 :)

**Comment by samr85** [comment]
Trying to read up, I have absolutely no idea what's causing this... Everything appears to be fine, it just doesn't serve anything...

**Comment by wjd52** [comment]
Let's close this. It might be fixed in the next version of tornado, but for now we'll just note it.
